#!/bin/bash

set -e

output="$1"
entry="$2"
included=()

if [[ -z "$output" || -z "$entry" ]]; then
  echo "Usage: $0 <output-file.sh> <entry-file.sh>"
  exit 1
fi

touch "$output"
> "$output"
echo "#!/bin/bash" > "$output"
echo "" >> "$output"
echo "# Generated by bundle.sh from $entry" >> "$output"
echo "" >> "$output"

resolve_path() {
  local parent="$1"
  local relpath="$2"
  local dir
  dir="$(cd "$(dirname "$parent")" && pwd)"
  realpath="$dir/$relpath"
  echo "$realpath"
}

bundle_file() {
  local file="$1"
  local abs_file
  abs_file="$(realpath "$file")"

  for included_file in "${included[@]}"; do
    if [[ "$included_file" == "$abs_file" ]]; then
      return
    fi
  done

  included+=("$abs_file")

  echo "# --- START: $file ---" >> "$output"

  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^source\ \"\\?\$?\(dirname\ \"\$0\"\)/([^\"]+)\" ]]; then
      relative="${BASH_REMATCH[1]}"
      resolved="$(resolve_path "$file" "$relative")"
      bundle_file "$resolved"
    elif [[ "$line" =~ ^source\ \"([^\"]+)\" ]]; then
      resolved="$(resolve_path "$file" "${BASH_REMATCH[1]}")"
      bundle_file "$resolved"
    elif [[ "$line" =~ ^#! ]]; then
      continue  # skip shebang
    else
      echo "$line" >> "$output"
    fi
  done < "$file"

  echo "# --- END: $file ---" >> "$output"
  echo "" >> "$output"
}

bundle_file "$entry"
chmod +x "$output"
echo "✅ Output written to $output"
