name: Release

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      PASSPHRASE:
        required: true
      TOKEN:
        required: true

permissions:
  contents: read

jobs:
  # Release
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # write
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      # Harden Runner
      - name: Harden Runner # Audit all outbound calls
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      # Checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # All commits need to be analyzed
          token: ${{ secrets.TOKEN }}

      # Import GPG
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        with:
          # git_commit_gpgsign: true
          # git_tag_gpgsign: true
          git_user_signingkey: true
          git_committer_name: ${{ vars.GIT_COMMITTER_NAME }}
          git_committer_email: ${{ vars.GIT_COMMITTER_EMAIL }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*

      # Clean Install
      - name: Clean Install
        run: npm ci

      # Build Source Code
      - name: Build Source Code
        run: npm run build

      # Release and Publish to NPM
      - name: Release and Publish to NPM
        run: npx semantic-release -e ./.github/workflows/helpers/release/release.config.mjs

      # # Echo Helpers
      # - name: Echo Helpers
      #   run: |
      #     echo $0
      #     printenv
      #     cat ~/.profile
      #     cat ~/.bashrc

      # # Echo Bagong
      # - name: Echo Bagong
      #   run: echo $BAGONG

      # Echo Next Release Version
      - name: Echo Next Release Version
        run: . $HOME/.profile && echo $NEXT_RELEASE_VERSION

      # Rebase Development Branch
      - name: Rebase Development Branch
        run: |
          git checkout dev
          git pull --rebase origin main
          git push --force origin dev
